services:
  # SERVIÇO 1: O Cérebro (Webserver + Banco + Usuário)
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # O PULO DO GATO: Este comando inicializa o banco, cria o admin e só depois sobe o servidor.
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname System --role Admin --email admin@rodou.gov.br || true &&
      airflow webserver"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Sao_Paulo
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=Uqv6pwYWJn7xifR3QAkifMTkupos8mkxaQL2Q7Ydsqw=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__BASE_URL=http://airflow-webserver:8080
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      # Variáveis do ro-DOU
      - RO_DOU__DAG_CONF_DIR=/opt/airflow/dags/ro_dou/dag_confs
      - AIRFLOW_VAR_PATH_TMP=/tmp
      - AIRFLOW_VAR_EMAIL_ADMIN=admin@rodou.gov.br
      - AIRFLOW_CONN_INLABS_DB=postgres://airflow:airflow@postgres:5432/airflow?schema=inlabs
    volumes:
      - airflow_logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
    # Mapeando a porta externa 8090 para a 8080 do container
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 180s

  # SERVIÇO 2: O Operário (Scheduler)
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: airflow scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Sao_Paulo
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=Uqv6pwYWJn7xifR3QAkifMTkupos8mkxaQL2Q7Ydsqw=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - RO_DOU__DAG_CONF_DIR=/opt/airflow/dags/ro_dou/dag_confs
      - AIRFLOW_VAR_PATH_TMP=/tmp
      - AIRFLOW_VAR_EMAIL_ADMIN=admin@rodou.gov.br
      - AIRFLOW_CONN_INLABS_DB=postgres://airflow:airflow@postgres:5432/airflow?schema=inlabs
    volumes:
      - airflow_logs:/opt/airflow/logs
    depends_on:
      airflow-webserver:
        condition: service_healthy

  # SERVIÇO 3: Banco de Dados
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dag_load_inlabs/sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  # SERVIÇO 4: SMTP Fake
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    #ports:
    #  - "5001:80"
    environment:
      - ServerOptions__HostName=smtp4dev
    # NÃO use ports (5001:80) se for usar domínio, para evitar conflito.
    # O Traefik acessa a porta interna (80) diretamente.
    expose:
      - "80"
      - "25"
    labels:
      - "traefik.enable=true"
      # Define que este container responde EXCLUSIVAMENTE por este domínio
      - "traefik.http.routers.smtp4dev.rule=Host(`airflowsmtp4dev.vps.avaliadoc.com.br`)"
      # Define que a porta para a Interface Web é a 80 (não a 25)
      - "traefik.http.services.smtp4dev.loadbalancer.server.port=80"
      # Configurações padrão do Coolify para HTTPS (entrypoint https/websecure)
      - "traefik.http.routers.smtp4dev.entrypoints=websecure"
      - "traefik.http.routers.smtp4dev.tls.certresolver=letsencrypt"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      retries: 3  

volumes:
  postgres_data:
  airflow_logs: