services:
  # SERVIÇO 1: O Cérebro (Webserver + Banco + Usuário)
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname System --role Admin --email ${GMAIL_USER} || true &&
      airflow webserver"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Sao_Paulo
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=Uqv6pwYWJn7xifR3QAkifMTkupos8mkxaQL2Q7Ydsqw=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__BASE_URL=http://airflow-webserver:8080
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      # Variáveis do ro-DOU
      - RO_DOU__DAG_CONF_DIR=/opt/airflow/dags/ro_dou/dag_confs
      - AIRFLOW_VAR_PATH_TMP=/tmp
      - AIRFLOW_VAR_EMAIL_ADMIN=${GMAIL_USER}
      - AIRFLOW_CONN_INLABS_DB=postgres://airflow:airflow@postgres:5432/airflow?schema=inlabs
      
      # --- CONFIGURAÇÃO DO GMAIL (Variáveis de Ambiente) ---
      - AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_STARTTLS=true
      - AIRFLOW__SMTP__SMTP_SSL=false
      - AIRFLOW__SMTP__SMTP_USER=${GMAIL_USER}
      - AIRFLOW__SMTP__SMTP_PASSWORD=${GMAIL_APP_PASS}
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=${GMAIL_USER}
      # -----------------------------------------------------

    volumes:
      - airflow_logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 180s

  # SERVIÇO 2: O Operário (Scheduler)
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: airflow scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Sao_Paulo
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=Uqv6pwYWJn7xifR3QAkifMTkupos8mkxaQL2Q7Ydsqw=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - RO_DOU__DAG_CONF_DIR=/opt/airflow/dags/ro_dou/dag_confs
      - AIRFLOW_VAR_PATH_TMP=/tmp
      - AIRFLOW_VAR_EMAIL_ADMIN=${GMAIL_USER}
      - AIRFLOW_CONN_INLABS_DB=postgres://airflow:airflow@postgres:5432/airflow?schema=inlabs
      
      # --- CONFIGURAÇÃO DO GMAIL (Replicar aqui também) ---
      - AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_STARTTLS=true
      - AIRFLOW__SMTP__SMTP_SSL=false
      - AIRFLOW__SMTP__SMTP_USER=${GMAIL_USER}
      - AIRFLOW__SMTP__SMTP_PASSWORD=${GMAIL_APP_PASS}
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=${GMAIL_USER}
      # ----------------------------------------------------

    volumes:
      - airflow_logs:/opt/airflow/logs
    depends_on:
      airflow-webserver:
        condition: service_healthy

  # SERVIÇO 3: Banco de Dados
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dag_load_inlabs/sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:
  airflow_logs: